export const img: { [key: string] : string } = {
	cursor_no: new URL('./img/cursor/no.svg', import.meta.url).href,
	cursor_default: new URL('./img/cursor/norm.svg', import.meta.url).href,
	cursor_pointer: new URL('./img/cursor/pointer.svg', import.meta.url).href,
	cursor_wait: new URL('./img/cursor/wait.svg', import.meta.url).href,
	boop_plusOne: new URL('./img/clickEffects/plusOne.svg', import.meta.url).href,
	boop_minusOne: new URL('./img/clickEffects/minusOne.svg', import.meta.url).href,
	boop_coin: new URL('./img/clickEffects/coin.svg', import.meta.url).href,
	boop_bean: new URL('./img/clickEffects/bean.svg', import.meta.url).href,
	boop_plus: new URL('./img/clickEffects/plus.svg', import.meta.url).href,
	boop_minus: new URL('./img/clickEffects/minus.svg', import.meta.url).href,
	boop_star: new URL('./img/clickEffects/star.svg', import.meta.url).href,
	boop_num1: new URL('./img/clickEffects/num1.svg', import.meta.url).href,
	boop_num2: new URL('./img/clickEffects/num2.svg', import.meta.url).href,
	boop_num3: new URL('./img/clickEffects/num3.svg', import.meta.url).href,
	boop_num4: new URL('./img/clickEffects/num4.svg', import.meta.url).href,
	boop_num5: new URL('./img/clickEffects/num5.svg', import.meta.url).href,
	boop_num6: new URL('./img/clickEffects/num6.svg', import.meta.url).href,
	boop_num7: new URL('./img/clickEffects/num7.svg', import.meta.url).href,
	boop_num8: new URL('./img/clickEffects/num8.svg', import.meta.url).href,
	boop_num9: new URL('./img/clickEffects/num9.svg', import.meta.url).href,
	boop_num0: new URL('./img/clickEffects/num0.svg', import.meta.url).href,
	boop_numDec: new URL('./img/clickEffects/numDec.svg', import.meta.url).href,
	boop_numPlus: new URL('./img/clickEffects/numPlus.svg', import.meta.url).href,
	tooltip: new URL('./img/tooltip.svg', import.meta.url).href,
};